import {useEffect,useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,Legend,AreaChart,Area} from 'recharts';
import {getHistory} from '../lib/api';
import {Activity,ArrowDownRight,ArrowUpRight,CalendarDays,Minus,Store,TrendingDown,TrendingUp} from 'lucide-react';

const palette=['#9dff72','#5be7ff','#ffcf70','#d59cff','#ff7eb6','#8fe3cf','#ffffff','#ff9b71'];
const money=n=>`₹${Number(n||0).toLocaleString('en-IN')}`;
const pct=n=>`${n>0?'+':''}${Number(n||0).toFixed(1)}%`;

export default function PriceChart({productId}){
 const [rows,setRows]=useState([]),[active,setActive]=useState('All'),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);setError('');getHistory(productId).then(r=>alive&&setRows(r)).catch(()=>alive&&setError('Price history is temporarily unavailable.')).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[productId]);
 const names=useMemo(()=>[...new Set(rows.map(r=>r.marketplace))],[rows]);
 const data=useMemo(()=>{const map=new Map();rows.forEach(r=>{const key=new Date(r.recorded_at).toISOString().slice(0,10);if(!map.has(key))map.set(key,{date:key});map.get(key)[r.marketplace]=r.price});return [...map.values()]},[rows]);
 const stats=useMemo(()=>names.map(n=>{const values=rows.filter(r=>r.marketplace===n).sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at)).map(r=>r.price);const current=values.at(-1)||0;const first=values[0]||current;const low=values.length?Math.min(...values):0;const high=values.length?Math.max(...values):0;return {name:n,current,first,low,high,change:first?((current-first)/first)*100:0,range:high-low}}),[rows,names]);
 const visible=active==='All'?names:names.filter(n=>n===active);
 const market=useMemo(()=>{if(!stats.length)return null;const all=rows.map(r=>r.price);const first=rows.slice().sort((a,b)=>new Date(a.recorded_at)-new Date(b.recorded_at))[0]?.price||0;const current=Math.min(...names.map(n=>stats.find(s=>s.name===n)?.current||Infinity));const low=Math.min(...all),high=Math.max(...all),avg=all.reduce((a,b)=>a+b,0)/all.length;const change=first?((current-first)/first)*100:0;return {current,low,high,avg,change}},[stats,rows,names]);
 if(loading)return <div className="chart-card chart-loading"><div className="loader"/><span>Building market movement intelligence…</span></div>;
 if(error||!rows.length)return <div className="chart-card"><div className="empty compact"><h3>No history available</h3><p>{error||'No historical observations are available for this product yet.'}</p></div></div>;
 return <div className="chart-card market-movement">
   <div className="chart-head"><div><span className="eyebrow">MARKET MOVEMENT / {data[0]?.date} → {data.at(-1)?.date}</span><h3>Where is the price moving?</h3><p>Compare store-by-store movement, historical ranges and the latest market signal.</p></div><select value={active} onChange={e=>setActive(e.target.value)}><option value="All">All stores</option>{names.map(n=><option key={n} value={n}>{n}</option>)}</select></div>
   <div className="market-kpis"><div><span><Activity size={13}/> Market low</span><b>{money(market.low)}</b><small>lowest observed</small></div><div><span><TrendingDown size={13}/> Current low</span><b>{money(market.current)}</b><small>best live comparison</small></div><div><span><CalendarDays size={13}/> Average</span><b>{money(market.avg)}</b><small>across observations</small></div><div><span><Store size={13}/> Store range</span><b>{money(market.high-market.low)}</b><small>{names.length} marketplaces</small></div></div>
   <div className="trend-banner"><div className="trend-orb"><Activity/></div><div><b>{market.change <= -3 ? 'Prices are trending lower' : market.change >= 3 ? 'Prices are trending higher' : 'Prices are moving within a tight band'}</b><p>Compared with the earliest observed market price, the current lowest offer is <strong>{pct(market.change)}</strong>. Use individual stores below to spot the widest spread.</p></div><span className={market.change<0?'trend-good':'trend-neutral'}>{market.change<0?<ArrowDownRight/>:market.change>0?<ArrowUpRight/>:<Minus/>}{pct(market.change)}</span></div>
   <div className="chart"><ResponsiveContainer width="100%" height={380}><LineChart data={data} margin={{top:16,right:22,left:10,bottom:10}}><CartesianGrid stroke="#ffffff12" vertical={false}/><XAxis dataKey="date" stroke="#657185" tick={{fontSize:11}} tickFormatter={v=>v.slice(5)}/><YAxis stroke="#657185" tick={{fontSize:11}} tickFormatter={v=>`₹${Math.round(v/1000)}k`} width={54}/><Tooltip contentStyle={{background:'#0c121b',border:'1px solid #ffffff18',borderRadius:12}} labelFormatter={v=>`Date: ${v}`} formatter={v=>money(v)}/><Legend wrapperStyle={{paddingTop:12}}/>{visible.map((n,i)=><Line key={n} type="monotone" dataKey={n} stroke={palette[names.indexOf(n)%palette.length]} strokeWidth={active==='All'?2:3} dot={false} connectNulls animationDuration={900}/>)}</LineChart></ResponsiveContainer></div>
   <div className="store-range-grid">{(active==='All'?stats:stats.filter(s=>s.name===active)).map((s,i)=><div className="store-range" key={s.name}><div className="store-range-top"><span><i style={{background:palette[names.indexOf(s.name)%palette.length]}}/>{s.name}</span><b>{money(s.current)}</b></div><div className="range-track"><i style={{left:`${s.high===s.low?50:((s.current-s.low)/(s.high-s.low))*100}%`}}/></div><div className="range-labels"><span>Low {money(s.low)}</span><span>High {money(s.high)}</span></div><small className={s.change<0?'down':''}>{s.change<0?<ArrowDownRight size={12}/>:s.change>0?<ArrowUpRight size={12}/>:<Minus size={12}/>} {pct(s.change)} since first observation · spread {money(s.range)}</small></div>)}</div>
   <p className="chart-note">Historical observations are portfolio/demo data. In production, this panel should be fed by authorized retailer or affiliate feeds and exact SKU matches.</p>
 </div>
}
