import {useEffect,useMemo,useState} from 'react';
import {useParams,useNavigate,Link} from 'react-router-dom';
import {getProduct,getHistory,api,isLoggedIn,addServerWishlist,removeServerWishlist,createPriceAlert} from '../lib/api';
import {openRetailer} from '../lib/offers';
import {motion} from 'framer-motion';
import {Heart,Bell,Star,Check,ShieldCheck,Truck,RotateCcw,ArrowLeft,RefreshCw,ExternalLink,Store,ArrowUpRight,X,Target} from 'lucide-react';
import PriceChart from '../components/PriceChart';
const readIds=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch{return[]}};
const writeIds=(k,ids)=>{localStorage.setItem(k,JSON.stringify(ids));window.dispatchEvent(new Event('shopsphere-storage'));};
export default function ProductDetail(){
 const {id}=useParams(),nav=useNavigate();const [p,setP]=useState(null),[history,setHistory]=useState([]),[alert,setAlert]=useState(''),[wish,setWish]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');const [alertOpen,setAlertOpen]=useState(false);const [alertMin,setAlertMin]=useState('');const [alertMax,setAlertMax]=useState('');const [alertSaving,setAlertSaving]=useState(false);
 useEffect(()=>{let alive=true;setLoading(true);setError('');Promise.all([getProduct(id),getHistory(id)]).then(([product,h])=>{if(alive){setP(product);setHistory(h);setWish(readIds('shopsphere_wishlist').includes(product.id))}}).catch(e=>alive&&setError(e.response?.data?.detail||'This product could not be loaded.')).finally(()=>alive&&setLoading(false));return()=>{alive=false}},[id]);
 const sorted=useMemo(()=>[...(p?.prices||[])].sort((a,b)=>a.price-b.price),[p]);const best=sorted[0];const min=best?.price||0;const maxDiscount=useMemo(()=>p?.prices?.length?Math.max(...p.prices.map(x=>x.discount_pct||0)):0,[p]);
 const toggleWish=async()=>{if(!p)return;const exists=readIds('shopsphere_wishlist').includes(p.id);try{if(isLoggedIn()){if(exists)await removeServerWishlist(p.id);else await addServerWishlist(p.id)}}catch{}const ids=readIds('shopsphere_wishlist');const next=exists?ids.filter(x=>x!==p.id):[...ids,p.id];writeIds('shopsphere_wishlist',next);setWish(!exists);setAlert(exists?'Removed from wishlist':'Saved to wishlist');};
 const shop=(offer=best)=>{if(!offer)return;openRetailer(offer.marketplace,p);setAlert(`Opening ${offer.marketplace} for ${p.name}`);};
 const openTracker=()=>{const current=Math.round(min);setAlertMin(String(Math.round(current*.90)));setAlertMax(String(current));setAlertOpen(true)};
 const saveAlert=async e=>{e.preventDefault();const lo=Number(alertMin),hi=Number(alertMax);if(!lo||!hi||hi<lo){setAlert('Enter a valid price range.');return}setAlertSaving(true);try{if('Notification' in window && Notification.permission==='default') {try{await Notification.requestPermission()}catch{}} let synced=false;if(isLoggedIn()){try{await createPriceAlert(p.id,lo,hi);synced=true}catch(apiErr){console.warn('Synced price alert failed; saving a local fallback.',apiErr)}}localStorage.setItem(`alert_${p.id}`,JSON.stringify({min:lo,max:hi,name:p.name,active:true,triggered:false,createdAt:new Date().toISOString()}));window.dispatchEvent(new Event('shopsphere-alerts'));setAlert(synced?`Alert synced: ₹${lo.toLocaleString('en-IN')}–₹${hi.toLocaleString('en-IN')}.`:`Alert saved on this browser: ₹${lo.toLocaleString('en-IN')}–₹${hi.toLocaleString('en-IN')}. Sign in again to sync across devices.`);setAlertOpen(false)}catch(e){setAlert('Could not save the price alert locally. Please try again.')}finally{setAlertSaving(false)}};
 if(loading)return <div className="loading"><div className="loader"/>Loading product intelligence...</div>;
 if(error||!p)return <section className="section empty-page"><div className="empty-icon">!</div><div className="eyebrow">PRODUCT UNAVAILABLE</div><h1>We couldn't open this product.</h1><p>{error||'The product no longer exists.'}</p><div className="fatal-actions"><button className="primary" onClick={()=>nav('/products')}>Back to catalog</button><button className="secondary" onClick={()=>window.location.reload()}><RefreshCw size={15}/> Retry</button></div></section>;
 return <section className="detail-page"><motion.button className="back-button detail-back" whileHover={{x:-5,scale:1.02}} whileTap={{scale:.96}} onClick={()=>nav(-1)}><ArrowLeft size={16}/> Back</motion.button><div className="breadcrumbs"><Link to="/products"><ArrowLeft size={14}/> Products</Link><span>/</span><span>{p.category}</span><span>/</span><b>{p.name}</b></div>
  <div className="detail-grid"><motion.div className="detail-visual" initial={{opacity:0,x:-35}} animate={{opacity:1,x:0}}><div className="detail-img"><img src={p.image_url} alt={p.name}/><span className="detail-badge">{maxDiscount}% max reference discount</span></div><div className="micro-trust"><span><ShieldCheck/> Comparison reference data</span><span><Truck/> Delivery set by retailer</span><span><RotateCcw/> Returns set by retailer</span></div></motion.div>
   <motion.div className="detail-copy" initial={{opacity:0,x:35}} animate={{opacity:1,x:0}}><div className="eyebrow">{p.brand} · {p.category}</div><h1>{p.name}</h1><div className="rating"><Star size={16} fill="currentColor"/> {p.rating} customer rating <span>·</span> {p.prices.length} retailer offers</div><p>{p.description}</p><div className="big-price">₹{min.toLocaleString('en-IN')} <span>lowest comparison offer</span></div>
    <div className="actions"><button onClick={toggleWish} className={wish?'active-action':''}><Heart size={18} fill={wish?'currentColor':'none'}/> {wish?'Saved':'Wishlist'}</button><button className="primary" onClick={()=>shop(best)}><ExternalLink size={18}/> Shop lowest price</button><button className="track-btn" onClick={openTracker}><Bell size={18}/> Set price alert</button></div>{alert&&<motion.div initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className="toast"><Check size={16}/> {alert}</motion.div>}
   </motion.div></div>
  {alertOpen&&<div className="modal-backdrop" onMouseDown={()=>setAlertOpen(false)}><motion.div className="alert-modal" initial={{opacity:0,y:20,scale:.97}} animate={{opacity:1,y:0,scale:1}} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setAlertOpen(false)}><X size={16}/></button><div className="modal-icon"><Target/></div><div className="eyebrow">PRICE TARGET</div><h2>Tell ShopSphere your buying range.</h2><p className="muted">We'll check the lowest available comparison offer. When the price enters your range, the alert fires once, pauses to prevent notification spam, and can be reactivated from Price Alerts.</p><form className="alert-form" onSubmit={saveAlert}><label>Minimum price<input type="number" min="1" value={alertMin} onChange={e=>setAlertMin(e.target.value)} placeholder="₹90,000"/></label><label>Maximum price<input type="number" min="1" value={alertMax} onChange={e=>setAlertMax(e.target.value)} placeholder="₹1,00,000"/></label><button className="primary" disabled={alertSaving}>{alertSaving?'Saving…':<><Bell size={15}/> Activate alert</>}</button></form><div className="alert-quick"><button type="button" onClick={()=>{setAlertMin(String(Math.round(min*.95)));setAlertMax(String(Math.round(min)))}}>5% below → current</button><button type="button" onClick={()=>{setAlertMin(String(Math.round(min*.90)));setAlertMax(String(Math.round(min*.95)))}}>10–5% below</button><button type="button" onClick={()=>{setAlertMin(String(Math.round(min*.85)));setAlertMax(String(Math.round(min*.90)))}}>15–10% below</button></div></motion.div></div>}
  <section className="comparison-section"><div className="section-head"><div><div className="eyebrow">MULTI-RETAILER COMPARISON</div><h2>Choose the offer you want</h2><p className="muted">Compare the reference offers below. Select any retailer to continue directly to its website.</p></div><span className="compare-count">{p.prices.length} offers</span></div><div className="comparison-table"><div className="compare-row compare-header"><span>Retailer</span><span>Price</span><span>Discount</span><span>Action</span></div>{sorted.map((x,i)=><motion.div className={i===0?'compare-row best-row':'compare-row'} key={x.marketplace} initial={{opacity:0,x:-15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.04}}><span><b>{x.marketplace}</b>{i===0&&<em>Lowest offer</em>}</span><strong>₹{x.price.toLocaleString('en-IN')}</strong><span className="discount">{x.discount_pct}% off</span><span className="store-action"><button className="offer-link" onClick={()=>shop(x)}><Store size={14}/> Shop at {x.marketplace} <ArrowUpRight size={13}/></button></span></motion.div>)}</div><div className="outbound-note"><ExternalLink size={15}/> ShopSphere compares offers; checkout, delivery, payment, returns and order fulfilment happen on the selected retailer's site.</div></section>
  <section className="chart-section"><div className="section-head"><div><div className="eyebrow">PRICE TRACKING</div><h2>Price history</h2><p className="muted">Use the store selector to isolate one marketplace, or compare all stores.</p></div></div><PriceChart productId={p.id}/></section>
  <section className="insight-grid"><div><div className="eyebrow">SHOPPING SIGNALS</div><h3>Comparison snapshot</h3><div className="signal"><span>Lowest offer</span><b>₹{min.toLocaleString('en-IN')}</b></div><div className="signal"><span>Highest discount</span><b>{maxDiscount}%</b></div><div className="signal"><span>Retailer coverage</span><b>{p.prices.length} offers</b></div></div><div><div className="eyebrow">DATA NOTE</div><h3>How retailer links work</h3><p className="muted">This portfolio build uses a realistic market-feed simulation: each retailer has an independent offer and the background updater moves prices over time. Production should replace the simulation with approved retailer feeds or affiliate APIs and exact SKU URLs.</p></div></section>
 </section>
}
